from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainPage, name='mainPage'),
    path('about/', views.aboutPage, name='aboutPage'),
    path('signUp/', views.signUp, name='signUp'),
    path('signIn/', views.signIn, name='signIn'),
    path('signOut/', views.signOut, name='signOut'),
    path('product/<int:id>/', views.productDetail, name='product'),
    path('settings/', views.settings, name='settings'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('adminPanel/', views.adminPage, name='adminPage'),
    path('adminPanel/sales/', views.salesPage, name='sales'),
    path('adminPanel/salesReport/', views.generate_sales_report, name='generate_sales_report'),
    path('adminPanel/cities/', views.citiesPage, name='cities'),
    path('adminPanel/cities/addCity/', views.addCity, name='addCity'),
    path('adminPanel/cities/deleteCity/<int:id>/', views.deleteCity, name='deleteCity'),
    path('adminPanel/cities/editCity/<int:id>/', views.editCity, name='editCity'),
    path('adminPanel/categories/', views.categoriesPage, name='categories'),
    path('adminPanel/categories/addCategory/', views.addCategory, name='addCategory'),
    path('adminPanel/categories/deleteCategory/<int:id>/', views.deleteCategory, name='deleteCategory'),
    path('adminPanel/categories/editCategory/<int:id>/', views.editCategory, name='editCategory'),
    path('adminPanel/adminProducts', views.adminProducts, name='adminProducts'),
    path('adminPanel/deleteProduct/<int:id>/', views.adminDeleteProduct, name='adminDeleteProduct'),
    path('adminPanel/addProduct/', views.adminAddProduct, name='adminAddProduct'),
    path('adminPanel/editProductMultiImgae/<int:id>/', views.adminMultiImageProduct, name='editProductMultiImgae'),
    path('adminPanel/editProductMultiImgae/adminDeleteMultiImageProduct/<int:id>/', views.adminDeleteMultiImageProduct, name='adminDeleteMultiImageProduct'),
    path('adminPanel/editProduct/<int:id>/', views.adminEditProduct, name='adminEditProduct'),
    path('adminPanel/users/', views.usersPage, name='usersPage'),
    path('adminPanel/users/<int:id>/', views.userInfo, name='userInfo'),
    path('adminPanel/Orders/', views.adminOrders, name='adminOrders'),
    path('adminPanel/Orders/adminOrdersUpdate/<int:id>/', views.adminOrdersUpdate, name='adminOrdersUpdate'),
    path('cart/', views.cart, name='cart'),
    path('cart/deleteFromCart/<int:id>/', views.deleteFromCart, name='cartDelete'),
    path('orders/', views.orders, name='orders'),
    path('orders/deleteOrder/<int:id>/', views.deleteOrder, name='deleteOrder'),
    path('orders/orderDetail/<int:id>/', views.orderDetail, name='orderDetail'),
]
