# Generated by Django 4.2.15 on 2024-09-21 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_theme_about2'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='about2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
