# Generated by Django 4.2.15 on 2024-09-29 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_userproductorder_order_id_userproductorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('بانتظار التأكيد', 'بانتظار التأكيد'), ('تم التأكيد', 'تم التأكيد'), ('تم التسليم', 'تم التسليم')], default='بانتظار التأكيد', max_length=30)),
                ('address', models.TextField()),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
