# Generated by Django 4.2.15 on 2024-09-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_city_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone2',
        ),
    ]
