# Generated by Django 4.2.15 on 2024-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_orders_user_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
