# Generated by Django 4.2.15 on 2024-10-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_hitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hitcount',
        ),
    ]
