# Generated by Django 4.2.15 on 2024-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_delete_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
