# Generated by Django 4.2.15 on 2024-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_product_number_of_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(choices=[('', ''), ('+972', '+972'), ('+970', '+970')], default='', max_length=15),
        ),
    ]
