# Generated by Django 4.2.15 on 2024-10-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_customuser_is_authenticated_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_authenticated',
        ),
    ]
