# Generated by Django 4.2.15 on 2024-10-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_customuser_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_authenticated',
        ),
    ]
