# Generated by Django 4.2.15 on 2024-10-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_remove_customuser_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
